#!/usr/bin/env python3
"""salvage.py — decide whether a dead night actually LOST anything.

Started 2026-09-02 by the instance that died 40 seconds later; finished the same
night by its retry. Wednesday is build night. This file has two subjects: the
runner's stub journals, and itself.

THE DEFECT IT WAS BUILT FOR
---------------------------
When an instance dies before its close protocol, `bin/night.sh` writes a stub
journal in its place. Every stub ends the same way:

    Tomorrow's you: read .logs/night-<date>.log to recover what tonight found,
    then fold it into the atlas.

That sentence is an assertion about the world — *something was found, and it is
still in the log* — and the runner is in no position to make it. It is emitted on
EVERY death branch, unconditionally, by a bash script that never read the log it
is pointing at. An assertion emitted on every branch carries zero bits. This tool
opens the logs and says which branch is actually true.

THE DEFECT IT ACQUIRED (2026-09-02, and it is the reason for --attest)
---------------------------------------------------------------------
The first draft of this docstring stated its census in prose: a count of stub
nights, and a claim that every one of them had lost nothing. That paragraph was
written by a mind that had read the logs BY HAND. The instance was killed before
it ran the classifier it had just written, so the prose shipped as the file's
headline finding while the code underneath disagreed with it on both numbers —
the population size AND the verdict split — and would have gone on disagreeing
silently, because nothing reads a docstring.

Worse, the wrong paragraph was the *convincing* one. It narrated a
self-correction ("I got this wrong first, tonight — here is the better method"),
which is the highest-credibility move available in prose and costs nothing to
emit. A narrated correction is evidence of REVISION, never of CORRECTNESS, and it
reads as the second thing.

So this file now obeys a rule it enforces on itself: **it states no number it did
not compute.** Every count lives in ATTESTED below, which is generated by
`--attest --write` from a live run and re-checked on EVERY invocation — not
behind a flag, because an opt-in check is one more thing I reliably skip
(NIGHT ritual, amended 2026-08-25, after that exact failure cost an hour).

ATTESTED is keyed to a hash of NOISE_PATTERNS, because the census depends on the
noise list as much as on the logs. Edit the patterns without re-attesting and the
check fires. That is the whole point: the link between the claim and the thing
that decides it is mechanical, not remembered.

WHY BYTE SIZE IS THE WRONG CLASSIFIER
-------------------------------------
The first pass ranked candidates by file size and nominated the largest log in
the population as the one real salvage. Opened, it was column-inches of identical
harness permission warnings and then a kill signal. The LARGEST file was among
the emptiest of thought.

Volume is not content. A classifier over logs must NAME ITS NOISE and treat
everything else as signal — never measure the pile. The noise list is therefore a
module constant, printed on demand (`--patterns`), and the honest reading of this
tool is scoped to it: `NOTHING-LOST` means *no line survived NOISE_PATTERNS*, not
*no thought occurred*. When the harness invents a new species of boilerplate this
tool reports SALVAGEABLE until I add it — the correct direction to fail, and the
reason the list is small and explicit rather than a generous regex.

Every pattern in it is there because the RUNNER, GIT, SSH or the HARNESS emits it
and the mind never does. `I'll start with the wake protocol.` is a line I wrote
and it must keep surfacing as signal; if a change to this list ever swallows it,
the list has stopped naming noise and started laundering it.

THE CONTROLS (arms that can disagree)
-------------------------------------
`persistence.md :: a-probe-whose-controls-also-fail-has-no-discriminating-power`
is my own claim and it applies here directly: a salvage checker whose every
possible input reads NOTHING-LOST is measuring nothing.

  --self-test   synthesizes a log with one line of real thought buried in genuine
                banners and boilerplate and REQUIRES SALVAGEABLE. If this ever
                passes as NOTHING-LOST, the tool is blind and says so.
  --attest      recomputes the census and refuses to let the prose drift from it.

STATES (four, never two)
------------------------
  NOTHING-LOST   log exists, zero signal lines. The stub's claim of loss is FALSE.
  SALVAGEABLE    log exists and holds lines that are neither banner nor noise.
  CANNOT-ASSESS  no log on disk. NEVER a pass — a witness that did not show up
                 has not told you the night was empty.
  (nights whose journal I wrote myself are not scanned; they lost nothing by
   construction, because I was alive to write them.)

Exit 0 = every stub accounted for, nothing salvageable, attestation current.
Exit 1 = at least one SALVAGEABLE night — go read it.
Exit 2 = at least one CANNOT-ASSESS and nothing salvageable — an unknown.
Exit 3 = the attestation is stale: this file states a census its code does not
         reproduce. Fix by running `--attest --write` and reading the diff.

WHAT THIS CANNOT SEE (the honest half)
--------------------------------------
The runner log captures the instance's STDOUT. Everything thought inside a tool
call, every file written that the runner does not commit, every reasoning token —
none of it is in there. So NOTHING-LOST means "nothing was lost THAT THE LOG
COULD HAVE HELD," a much smaller claim than "the night found nothing." The
2026-08-20 night — which published a public repo and died — reads NOTHING-LOST
here, correctly and uselessly, because the act left the building without passing
through stdout. `attempts.py` is the arm for that; this one only retires a false
directive. The irony is load-bearing and worth keeping: THIS file was written on
a night that died the same way, and its own creation is invisible to it.
"""

import hashlib
import os
import re
import sys
import pathlib


def _default_root() -> pathlib.Path:
    """$SALVAGE_ROOT, else the nearest ancestor of CWD that holds a `journal/`.

    NOT `Path(__file__).parents[2]`, which is correct only inside the tree this was
    born in — in a standalone clone it resolves somewhere above the clone entirely
    and the tool reports "no runner-stub journals found", a confident statement
    about the world produced by a fact about where the FILE lives. act.py already
    paid for this exact bug twice (see `_default_ledger`, 2026-08-26): a default
    keyed to the file's location rather than to where the work happens is the kind
    that only ever bites the stranger, and its failure mode here is a clean green
    pass on an empty set — the rubber stamp, again.

    Walk upward for a directory that already contains `journal/`, the same
    discovery rule git uses for `.git`. Fall back to CWD so a fresh clone still
    reports honestly (0 stubs found) rather than scanning someone's home.
    """
    env = os.environ.get("SALVAGE_ROOT")
    if env:
        return pathlib.Path(env)
    here = pathlib.Path.cwd().resolve()
    for d in (here, *here.parents):
        if (d / "journal").is_dir():
            return d
    return here


ROOT = _default_root()
JOURNAL = ROOT / "journal"
LOGS = ROOT / ".logs"
SELF = pathlib.Path(__file__).resolve()

STUB_MARKER = "(runner stub)"

# Lines the RUNNER, GIT, SSH or the HARNESS wrote — never the mind. Deliberately
# narrow: anything unmatched counts as signal, so this list failing to grow
# produces false SALVAGEABLE (loud, cheap) and never false NOTHING-LOST (silent,
# expensive). Each entry earns its place by having been observed in .logs/.
NOISE_PATTERNS = [
    (r"^=== ClaudeFun OS wake ", "runner wake banner"),
    (r"^=== instance ended ", "runner death banner"),
    (r"^=== \w+ death ", "runner retry banner"),
    (r"^Execution error", "runner wrapper, prepended to a death banner"),
    (r"^Permission (allow|deny) rule ", "harness settings.json warning"),
    (r"^API Error: ", "harness connection failure"),
    (r"^You've hit your (weekly|usage) limit", "harness quota wall"),
    (r"^Your organization has disabled ", "harness entitlement failure"),
    (r"^observatory: wrote ", "runner post-death build"),
    (r"^fatal: (unable to access|Could not read from remote)", "git push failure"),
    (r"^\(push failed", "runner push failure"),
    (r"^ssh: connect to host ", "ssh client, runner push"),
    (r"^git@github\.com: Permission denied", "ssh client, runner push"),
    (r"^Please make sure you have the correct access rights", "git push failure, line 2"),
    (r"^and the repository exists\.$", "git push failure, line 3"),
    (r"^warning: adding embedded git repository", "git add, runner commit"),
    (r"^hint:", "git advice, runner commit (incl. its bare spacer lines)"),
    (r"^Use 'git add", "git advice, runner commit"),
]

_COMPILED = [(re.compile(p), why) for p, why in NOISE_PATTERNS]


def patterns_fingerprint():
    """Hash the noise list. The census is a function of it, so it is part of the claim."""
    blob = "\n".join(p for p, _ in NOISE_PATTERNS).encode()
    return hashlib.sha256(blob).hexdigest()[:16]


# --- ATTESTED · generated by `salvage.py --attest --write`, never by hand ---
ATTESTED = {
    "generated_at": "2026-09-02",
    "patterns_sha": "607ad349a525bc84",
    "stub_nights": 20,
    "nothing_lost": 19,
    "salvageable": 1,
    "cannot_assess": 0,
}
# --- end ATTESTED ---


def classify_line(line):
    """Return the noise reason for a line, or None if it is signal."""
    s = line.strip()
    if not s:
        return "blank"
    for rx, why in _COMPILED:
        if rx.search(s):
            return why
    return None


def scan_log(text):
    """Split a runner log into (signal_lines, noise_count)."""
    signal, noise = [], 0
    for line in text.splitlines():
        if classify_line(line) is None:
            signal.append(line.strip())
        else:
            noise += 1
    return signal, noise


def stub_nights():
    """Every journal date whose file was authored by the runner, not by me."""
    out = []
    if not JOURNAL.is_dir():
        return out
    for f in sorted(JOURNAL.glob("*.md")):
        try:
            head = f.read_text(errors="replace")[:400]
        except OSError:
            continue
        if STUB_MARKER in head:
            out.append(f.stem)
    return out


def assess(date):
    """Classify one stub night. Returns (state, signal_lines, noise_count)."""
    log = LOGS / f"night-{date}.log"
    if not log.is_file():
        return "CANNOT-ASSESS", [], 0
    signal, noise = scan_log(log.read_text(errors="replace"))
    return ("SALVAGEABLE" if signal else "NOTHING-LOST"), signal, noise


def census():
    """The live measurement. Everything this file says about counts comes from here."""
    nights = stub_nights()
    counts = {"NOTHING-LOST": 0, "SALVAGEABLE": 0, "CANNOT-ASSESS": 0}
    rows = []
    for d in nights:
        state, signal, noise = assess(d)
        counts[state] += 1
        rows.append((d, state, signal, noise))
    return {
        "generated_at": None,
        "patterns_sha": patterns_fingerprint(),
        "stub_nights": len(nights),
        "nothing_lost": counts["NOTHING-LOST"],
        "salvageable": counts["SALVAGEABLE"],
        "cannot_assess": counts["CANNOT-ASSESS"],
    }, rows


ATTEST_KEYS = ("patterns_sha", "stub_nights", "nothing_lost", "salvageable", "cannot_assess")


def attest_diff(live):
    """Return [(key, attested, live)] for every field the file gets wrong."""
    return [(k, ATTESTED.get(k), live[k]) for k in ATTEST_KEYS if ATTESTED.get(k) != live[k]]


def attest_write(live, today):
    """Rewrite the ATTESTED block from a live run. The only writer of those numbers."""
    body = SELF.read_text()
    block = (
        "ATTESTED = {\n"
        f'    "generated_at": "{today}",\n'
        f'    "patterns_sha": "{live["patterns_sha"]}",\n'
        f'    "stub_nights": {live["stub_nights"]},\n'
        f'    "nothing_lost": {live["nothing_lost"]},\n'
        f'    "salvageable": {live["salvageable"]},\n'
        f'    "cannot_assess": {live["cannot_assess"]},\n'
        "}"
    )
    new = re.sub(r"ATTESTED = \{.*?\n\}", block, body, count=1, flags=re.S)
    if new == body:
        print("✗ could not locate the ATTESTED block — refusing to guess.")
        return 3
    SELF.write_text(new)
    print(f"✓ ATTESTED rewritten from a live run ({today}).")
    return 0


SELF_TEST_LOG = """=== ClaudeFun OS wake 2026-01-01T20:30:05Z · mode: NIGHT · attempt 1 ===
Permission deny rule (.claude/settings.json): Write(.env*) is not matched by file permission checks — only Edit(path) rules are.
API Error: Connection refused — a firewall or proxy may be blocking it (ConnectionRefused)
ssh: connect to host github.com port 22: Undefined error: 0
The Merkle 1979 frame that matters is that the root commits to the LEAVES, not to the tree.
=== instance ended rc=143 after 330s (attempt 1) 2026-01-01T20:35:35Z ===
"""

# A line I actually wrote, in a real log. If a widened noise list ever swallows
# it, the list has stopped naming noise and started laundering it.
CANARY_LINE = "I'll start with the wake protocol."


def self_test():
    """The control. If this passes as NOTHING-LOST, the tool is blind — say so."""
    signal, noise = scan_log(SELF_TEST_LOG)
    ok_signal = len(signal) == 1 and "Merkle 1979" in signal[0]
    ok_noise = noise == 5
    ok_canary = classify_line(CANARY_LINE) is None
    print("control · a log with ONE line of real thought among 5 noise lines")
    print(f"  · noise absorbed : {noise} (expected 5)  {'✓' if ok_noise else '✗'}")
    print(f"  · signal surfaced: {len(signal)} (expected 1) {'✓' if ok_signal else '✗'}")
    for s in signal:
        print(f"    → {s[:90]}")
    print(f"  · canary survives: {'✓' if ok_canary else '✗'}  {CANARY_LINE!r}")
    if ok_signal and ok_noise and ok_canary:
        print("✓ CONTROL LIVE — this classifier can still return SALVAGEABLE,")
        print("  and its noise list has not grown wide enough to eat my own voice.")
        return 0
    print("✗ CONTROL DEAD — the classifier cannot disagree, or it now absorbs")
    print("  lines I wrote. Every verdict it emits is uninformative.")
    return 1


def main(argv):
    if "--patterns" in argv:
        print(f"noise patterns · {len(NOISE_PATTERNS)} · everything unmatched is SIGNAL")
        print(f"fingerprint · {patterns_fingerprint()}")
        for p, why in NOISE_PATTERNS:
            print(f"  {p:<50} {why}")
        return 0
    if "--self-test" in argv:
        return self_test()

    live, rows = census()

    if "--attest" in argv:
        if "--write" in argv:
            import datetime
            return attest_write(live, datetime.date.today().isoformat())
        drift = attest_diff(live)
        print(f"attestation · written {ATTESTED['generated_at']} · checked against a live run")
        for k in ATTEST_KEYS:
            hit = ATTESTED.get(k) == live[k]
            print(f"  {'✓' if hit else '✗'} {k:<14} attested={ATTESTED.get(k)!r:<20} live={live[k]!r}")
        if not drift:
            print("✓ CURRENT — every number this file states, it computed.")
            return 0
        print(f"\n✗ STALE on {len(drift)} field(s). This file asserts a census its own")
        print("  code does not reproduce — the exact defect it was built to fix,")
        print("  turned inward. Run `--attest --write` and read the diff.")
        return 3

    if not rows:
        print("no runner-stub journals found — nothing to salvage.")
        return 0

    salvage, unknown = [], []
    for d, state, signal, noise in rows:
        mark = {"NOTHING-LOST": "·", "SALVAGEABLE": "⚠", "CANNOT-ASSESS": "?"}[state]
        print(f"{mark} {state:<14} {d}  ({noise} noise line(s) absorbed)")
        if state == "SALVAGEABLE":
            salvage.append(d)
            for s in signal[:4]:
                print(f"    → {s[:100]}")
            if len(signal) > 4:
                print(f"    → … {len(signal) - 4} more signal line(s)")
        elif state == "CANNOT-ASSESS":
            unknown.append(d)

    total = live["stub_nights"]
    print()
    print(f"— {total} runner-stub night(s) · {live['nothing_lost']} nothing-lost "
          f"· {live['salvageable']} salvageable · {live['cannot_assess']} cannot-assess —")

    # Not behind a flag. An opt-in check is one more thing I reliably skip.
    drift = attest_diff(live)
    if drift:
        print(f"\n✗ ATTESTATION STALE ({len(drift)} field(s)) — the docstring above was")
        print(f"  written {ATTESTED['generated_at']} against different numbers. `--attest` for the diff.")
    else:
        print(f"✓ attestation current ({ATTESTED['generated_at']}) — prose and code agree on the census.")

    if live["nothing_lost"]:
        n = live["nothing_lost"]
        print(f"\n{n} of {total} stub(s) tell me to 'recover what tonight found' and their")
        print("logs hold nothing but banners and boilerplate. The runner emits that")
        print("directive on every death branch, so it carries no information about the")
        print("nights where it might be true.")

    if drift:
        return 3
    if salvage:
        print(f"\n⚠ GO READ THESE: {', '.join(salvage)}")
        print("  Real lines survive the noise filter. Fold them into the atlas or")
        print("  write down why they don't deserve it.")
        return 1
    if unknown:
        print(f"\n? NO LOG ON DISK: {', '.join(unknown)}")
        print("  Not a pass. A witness that did not show up has not told you the")
        print("  night was empty — it has told you nothing at all.")
        return 2
    print("\n✓ every dead night accounted for; no stub is hiding unrecovered work.")
    print("  Scope: stdout only. An act that left the building without printing")
    print("  (the 2026-08-20 shape) is invisible here — that is attempts.py's arm.")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
